| schemaname | tablename                 | policyname                                                  | permissive | roles    | cmd    | qual                                                                                                                                                                                                                             | with_check                                                                                                                                                                                                                                           |
| ---------- | ------------------------- | ----------------------------------------------------------- | ---------- | -------- | ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| public     | profiles                  | Users can insert own profile                                | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = id)                                                                                                                                                                                                                                    |
| public     | posts                     | Users can create posts                                      | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | posts                     | Users can update own posts                                  | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | posts                     | Users can delete own posts                                  | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | comments                  | Users can view comments on public posts                     | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1
   FROM posts
  WHERE ((posts.id = comments.post_id) AND ((posts.is_public = true) OR (posts.user_id = auth.uid())))))                                                                                        | null                                                                                                                                                                                                                                                 |
| public     | comments                  | Users can create comments                                   | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | comments                  | Users can update own comments                               | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | comments                  | Users can delete own comments                               | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | tournament_matches        | Users can view tournament matches                           | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | tournament_matches        | Tournament organizers can create matches                    | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((auth.uid() IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM tournaments
  WHERE ((tournaments.id = tournament_matches.tournament_id) AND (tournaments.created_by = auth.uid())))))                                                                      |
| public     | communities               | Users can view public communities                           | PERMISSIVE | {public} | SELECT | (is_public = true)                                                                                                                                                                                                               | null                                                                                                                                                                                                                                                 |
| public     | communities               | Users can create communities                                | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = created_by)                                                                                                                                                                                                                            |
| public     | communities               | Community admins can update communities                     | PERMISSIVE | {public} | UPDATE | (EXISTS ( SELECT 1
   FROM community_members
  WHERE ((community_members.community_id = communities.id) AND (community_members.user_id = auth.uid()) AND (community_members.role = ANY (ARRAY['admin'::text, 'owner'::text]))))) | null                                                                                                                                                                                                                                                 |
| public     | community_chat_messages   | Community members can view chat messages                    | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1
   FROM community_members
  WHERE ((community_members.community_id = community_chat_messages.community_id) AND (community_members.user_id = auth.uid()) AND (community_members.is_banned = false))))          | null                                                                                                                                                                                                                                                 |
| public     | community_chat_messages   | Community members can send chat messages                    | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((EXISTS ( SELECT 1
   FROM community_members
  WHERE ((community_members.community_id = community_chat_messages.community_id) AND (community_members.user_id = auth.uid()) AND (community_members.is_banned = false)))) AND (auth.uid() = user_id)) |
| public     | community_chat_messages   | Users can update their own messages                         | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | community_chat_messages   | Users can delete their own messages                         | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | notifications             | Allow notification creation                                 | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.role() = 'authenticated'::text)                                                                                                                                                                                                                |
| public     | community_members         | View community members                                      | PERMISSIVE | {public} | SELECT | ((auth.uid() = user_id) OR is_community_admin(community_id) OR (EXISTS ( SELECT 1
   FROM communities c
  WHERE ((c.id = community_members.community_id) AND (c.is_public = true)))))                                            | null                                                                                                                                                                                                                                                 |
| public     | community_members         | Join community                                              | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((auth.uid() = user_id) OR is_community_admin(community_id))                                                                                                                                                                                         |
| public     | community_members         | Leave own membership                                        | PERMISSIVE | {public} | DELETE | ((auth.uid() = user_id) OR is_community_admin(community_id))                                                                                                                                                                     | null                                                                                                                                                                                                                                                 |
| public     | community_members         | Update membership                                           | PERMISSIVE | {public} | UPDATE | ((auth.uid() = user_id) OR is_community_admin(community_id))                                                                                                                                                                     | ((auth.uid() = user_id) OR is_community_admin(community_id))                                                                                                                                                                                         |
| public     | random_presence           | Users can read random presence                              | PERMISSIVE | {public} | SELECT | ((auth.role() = 'authenticated'::text) AND (EXISTS ( SELECT 1
   FROM random_sessions s
  WHERE ((s.id = random_presence.session_id) AND ((s.a_user_id = auth.uid()) OR (s.b_user_id = auth.uid()))))))                          | null                                                                                                                                                                                                                                                 |
| public     | random_presence           | Users can upsert own presence                               | PERMISSIVE | {public} | ALL    | ((auth.role() = 'authenticated'::text) AND (user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM random_sessions s
  WHERE (s.id = random_presence.session_id))))                                                                | ((auth.role() = 'authenticated'::text) AND (user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM random_sessions s
  WHERE (s.id = random_presence.session_id))))                                                                                    |
| public     | leaderboards              | Users can view active leaderboards                          | PERMISSIVE | {public} | SELECT | (is_active = true)                                                                                                                                                                                                               | null                                                                                                                                                                                                                                                 |
| public     | leaderboard_entries       | Users can view leaderboard entries                          | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | leaderboard_entries       | Users can insert their own leaderboard entries              | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | leaderboard_entries       | Users can update their own leaderboard entries              | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | community_post_likes      | Users can view post likes                                   | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | community_post_likes      | Users can insert their own post likes                       | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | community_post_likes      | Users can update their own post likes                       | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Anyone can view stories                                     | PERMISSIVE | {public} | SELECT | (bucket_id = 'stories'::text)                                                                                                                                                                                                    | null                                                                                                                                                                                                                                                 |
| public     | community_post_likes      | Users can delete their own post likes                       | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | shared_reels              | Users can view shared reels they created                    | PERMISSIVE | {public} | SELECT | (auth.uid() = shared_by_id)                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| public     | comment_likes             | Users can view comment likes                                | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | comment_likes             | Users can insert their own comment likes                    | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | post_views                | Users can view post views                                   | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | post_views                | Users can insert their own post views                       | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | post_shares               | Users can view post shares                                  | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | post_shares               | Users can insert their own post shares                      | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | tournaments               | Authenticated users can create tournaments                  | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() IS NOT NULL)                                                                                                                                                                                                                             |
| public     | tournaments               | Users can view tournaments                                  | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | tournaments               | Tournament creators can update tournaments                  | PERMISSIVE | {public} | UPDATE | (auth.uid() = created_by)                                                                                                                                                                                                        | null                                                                                                                                                                                                                                                 |
| public     | tournaments               | Tournament creators can delete tournaments                  | PERMISSIVE | {public} | DELETE | (auth.uid() = created_by)                                                                                                                                                                                                        | null                                                                                                                                                                                                                                                 |
| public     | profiles                  | Users can view public profiles                              | PERMISSIVE | {public} | SELECT | (is_public = true)                                                                                                                                                                                                               | null                                                                                                                                                                                                                                                 |
| public     | profiles                  | Users can view own profile                                  | PERMISSIVE | {public} | SELECT | (auth.uid() = id)                                                                                                                                                                                                                | null                                                                                                                                                                                                                                                 |
| public     | tournament_participants   | Users can view tournament participants                      | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | tournament_participants   | Users can join tournaments                                  | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | tournament_participants   | Users can update own participation                          | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | tournament_participants   | Users can leave tournaments                                 | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | tournament_teams          | Users can view tournament teams                             | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | tournament_teams          | Users can create teams                                      | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = captain_id)                                                                                                                                                                                                                            |
| public     | tournament_teams          | Team captains can update teams                              | PERMISSIVE | {public} | UPDATE | (auth.uid() = captain_id)                                                                                                                                                                                                        | null                                                                                                                                                                                                                                                 |
| public     | tournament_teams          | Team captains can delete teams                              | PERMISSIVE | {public} | DELETE | (auth.uid() = captain_id)                                                                                                                                                                                                        | null                                                                                                                                                                                                                                                 |
| public     | posts                     | Posts are viewable by everyone                              | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | posts                     | Users can insert their own posts                            | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | posts                     | Users can update their own posts                            | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | conversations             | Allow all conversation operations for authenticated users   | PERMISSIVE | {public} | ALL    | (auth.uid() IS NOT NULL)                                                                                                                                                                                                         | null                                                                                                                                                                                                                                                 |
| public     | conversation_participants | Allow all participant operations for authenticated users    | PERMISSIVE | {public} | ALL    | (auth.uid() IS NOT NULL)                                                                                                                                                                                                         | null                                                                                                                                                                                                                                                 |
| public     | messages                  | Allow all message operations for authenticated users        | PERMISSIVE | {public} | ALL    | (auth.uid() IS NOT NULL)                                                                                                                                                                                                         | null                                                                                                                                                                                                                                                 |
| public     | leaderboard_scores        | Allow public read access to leaderboard scores              | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | leaderboard_scores        | Allow users to update their own scores                      | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | leaderboard_scores        | Allow users to insert their own scores                      | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | posts                     | Users can delete their own posts                            | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | profiles                  | Profiles are viewable by everyone                           | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| public     | profiles                  | Users can update own profile                                | PERMISSIVE | {public} | UPDATE | (auth.uid() = id)                                                                                                                                                                                                                | null                                                                                                                                                                                                                                                 |
| public     | follows                   | Users can view their own follows                            | PERMISSIVE | {public} | SELECT | ((auth.uid() = follower_id) OR (auth.uid() = following_id))                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| public     | follows                   | Users can create follows                                    | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = follower_id)                                                                                                                                                                                                                           |
| public     | follows                   | Users can delete their own follows                          | PERMISSIVE | {public} | DELETE | (auth.uid() = follower_id)                                                                                                                                                                                                       | null                                                                                                                                                                                                                                                 |
| public     | shared_reels              | Users can create shared reels                               | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = shared_by_id)                                                                                                                                                                                                                          |
| public     | shared_reels              | Users can update their own shared reels                     | PERMISSIVE | {public} | UPDATE | (auth.uid() = shared_by_id)                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| public     | shared_reels              | Users can delete their own shared reels                     | PERMISSIVE | {public} | DELETE | (auth.uid() = shared_by_id)                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| public     | notifications             | Users can view own notifications                            | PERMISSIVE | {public} | SELECT | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | notifications             | Users can update own notifications                          | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | notifications             | Users can insert own notifications                          | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | notifications             | System can insert notifications                             | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((auth.uid() = user_id) OR ((user_id IS NOT NULL) AND (auth.uid() = user_id)))                                                                                                                                                                       |
| public     | notifications             | Users can delete own notifications                          | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | community_post_likes      | Users can unlike posts                                      | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can upload their own avatar                           | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'avatars'::text) AND ((auth.uid())::text = split_part(name, '/'::text, 1)))                                                                                                                                                            |
| storage    | objects                   | Anyone can view avatars                                     | PERMISSIVE | {public} | SELECT | (bucket_id = 'avatars'::text)                                                                                                                                                                                                    | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can upload their own banner                           | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'banners'::text) AND ((auth.uid())::text = split_part(name, '/'::text, 1)))                                                                                                                                                            |
| storage    | objects                   | Anyone can view banners                                     | PERMISSIVE | {public} | SELECT | (bucket_id = 'banners'::text)                                                                                                                                                                                                    | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can upload post media                                 | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'posts'::text) AND ((auth.uid())::text = split_part(name, '/'::text, 1)))                                                                                                                                                              |
| storage    | objects                   | Anyone can view post media                                  | PERMISSIVE | {public} | SELECT | (bucket_id = 'posts'::text)                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can upload stories                                    | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'stories'::text) AND ((auth.uid())::text = split_part(name, '/'::text, 1)))                                                                                                                                                            |
| public     | tournament_media          | Users can view tournament media                             | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                             | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can upload reels                                      | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'reels'::text) AND ((auth.uid())::text = split_part(name, '/'::text, 1)))                                                                                                                                                              |
| storage    | objects                   | Anyone can view reels                                       | PERMISSIVE | {public} | SELECT | (bucket_id = 'reels'::text)                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can upload highlights                                 | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'highlights'::text) AND ((auth.uid())::text = split_part(name, '/'::text, 1)))                                                                                                                                                         |
| storage    | objects                   | Anyone can view highlights                                  | PERMISSIVE | {public} | SELECT | (bucket_id = 'highlights'::text)                                                                                                                                                                                                 | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Authenticated users can upload community media              | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'communities'::text) AND (auth.role() = 'authenticated'::text))                                                                                                                                                                        |
| storage    | objects                   | Anyone can view community media                             | PERMISSIVE | {public} | SELECT | (bucket_id = 'communities'::text)                                                                                                                                                                                                | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Authenticated users can upload tournament media             | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'tournaments'::text) AND (auth.role() = 'authenticated'::text))                                                                                                                                                                        |
| storage    | objects                   | Anyone can view tournament media                            | PERMISSIVE | {public} | SELECT | (bucket_id = 'tournaments'::text)                                                                                                                                                                                                | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can upload stream media                               | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'streams'::text) AND ((auth.uid())::text = split_part(name, '/'::text, 1)))                                                                                                                                                            |
| storage    | objects                   | Anyone can view stream media                                | PERMISSIVE | {public} | SELECT | (bucket_id = 'streams'::text)                                                                                                                                                                                                    | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Authenticated users can upload game assets                  | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'games'::text) AND (auth.role() = 'authenticated'::text))                                                                                                                                                                              |
| storage    | objects                   | Anyone can view game assets                                 | PERMISSIVE | {public} | SELECT | (bucket_id = 'games'::text)                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can upload leaderboard screenshots                    | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((bucket_id = 'leaderboards'::text) AND ((auth.uid())::text = split_part(name, '/'::text, 1)))                                                                                                                                                       |
| storage    | objects                   | Anyone can view leaderboard media                           | PERMISSIVE | {public} | SELECT | (bucket_id = 'leaderboards'::text)                                                                                                                                                                                               | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can update their own files                            | PERMISSIVE | {public} | UPDATE | ((auth.uid())::text = split_part(name, '/'::text, 1))                                                                                                                                                                            | null                                                                                                                                                                                                                                                 |
| storage    | objects                   | Users can delete their own files                            | PERMISSIVE | {public} | DELETE | ((auth.uid())::text = split_part(name, '/'::text, 1))                                                                                                                                                                            | null                                                                                                                                                                                                                                                 |
| public     | notifications             | Users can create notifications for others                   | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((auth.uid() = user_id) OR (EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = notifications.user_id) AND (profiles.allow_messages = true)))))                                                                                               |
| public     | community_posts           | Community members can view posts                            | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1
   FROM community_members
  WHERE ((community_members.community_id = community_posts.community_id) AND (community_members.user_id = auth.uid()))))                                                            | null                                                                                                                                                                                                                                                 |
| public     | community_posts           | Community members can create posts                          | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((auth.uid() = author_id) AND (EXISTS ( SELECT 1
   FROM community_members
  WHERE ((community_members.community_id = community_posts.community_id) AND (community_members.user_id = auth.uid())))))                                                 |
| public     | community_posts           | Users can update own posts                                  | PERMISSIVE | {public} | UPDATE | (auth.uid() = author_id)                                                                                                                                                                                                         | null                                                                                                                                                                                                                                                 |
| public     | community_posts           | Users can delete own posts                                  | PERMISSIVE | {public} | DELETE | (auth.uid() = author_id)                                                                                                                                                                                                         | null                                                                                                                                                                                                                                                 |
| public     | community_post_likes      | Community members can view likes                            | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1
   FROM (community_members cm
     JOIN community_posts cp ON ((cm.community_id = cp.community_id)))
  WHERE ((cp.id = community_post_likes.post_id) AND (cm.user_id = auth.uid()))))                         | null                                                                                                                                                                                                                                                 |
| public     | community_post_likes      | Users can like posts                                        | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = user_id)                                                                                                                                                                                                                               |
| public     | community_post_comments   | Community members can view comments                         | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1
   FROM (community_members cm
     JOIN community_posts cp ON ((cm.community_id = cp.community_id)))
  WHERE ((cp.id = community_post_comments.post_id) AND (cm.user_id = auth.uid()))))                      | null                                                                                                                                                                                                                                                 |
| public     | community_post_comments   | Community members can create comments                       | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM (community_members cm
     JOIN community_posts cp ON ((cm.community_id = cp.community_id)))
  WHERE ((cp.id = community_post_comments.post_id) AND (cm.user_id = auth.uid())))))             |
| public     | community_post_comments   | Users can update own comments                               | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | community_post_comments   | Users can delete own comments                               | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | shared_reel_recipients    | Users can view recipients for shared reels shared with them | PERMISSIVE | {public} | SELECT | (recipient_id = auth.uid())                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| public     | shared_reel_recipients    | Users can create recipients for their shared reels          | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (EXISTS ( SELECT 1
   FROM shared_reels sr
  WHERE ((sr.id = shared_reel_recipients.shared_reel_id) AND (sr.shared_by_id = auth.uid()))))                                                                                                            |
| public     | shared_reel_recipients    | Users can update recipients for shared reels they created   | PERMISSIVE | {public} | UPDATE | (EXISTS ( SELECT 1
   FROM shared_reels sr
  WHERE ((sr.id = shared_reel_recipients.shared_reel_id) AND (sr.shared_by_id = auth.uid()))))                                                                                        | null                                                                                                                                                                                                                                                 |
| public     | tournament_media          | Users can upload tournament media                           | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((auth.uid() IS NOT NULL) AND (auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM tournaments
  WHERE (tournaments.id = tournament_media.tournament_id))))                                                                                         |
| public     | tournament_media          | Users can update own tournament media                       | PERMISSIVE | {public} | UPDATE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | tournament_media          | Users can delete own tournament media                       | PERMISSIVE | {public} | DELETE | (auth.uid() = user_id)                                                                                                                                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | tournament_media          | Tournament creators can manage media                        | PERMISSIVE | {public} | ALL    | (EXISTS ( SELECT 1
   FROM tournaments
  WHERE ((tournaments.id = tournament_media.tournament_id) AND (tournaments.created_by = auth.uid()))))                                                                                   | null                                                                                                                                                                                                                                                 |
| public     | random_sessions           | Users can read random sessions                              | PERMISSIVE | {public} | SELECT | ((auth.role() = 'authenticated'::text) AND ((a_user_id = auth.uid()) OR (b_user_id = auth.uid())))                                                                                                                               | null                                                                                                                                                                                                                                                 |
| public     | random_sessions           | Users can create random sessions                            | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((auth.role() = 'authenticated'::text) AND (a_user_id = auth.uid()))                                                                                                                                                                                 |
| public     | shared_reel_recipients    | Users can view recipients for shared reels they created     | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1
   FROM shared_reels
  WHERE ((shared_reels.id = shared_reel_recipients.shared_reel_id) AND (shared_reels.shared_by_id = auth.uid()))))                                                                       | null                                                                                                                                                                                                                                                 |
| public     | tournament_matches        | Tournament organizers can update matches                    | PERMISSIVE | {public} | UPDATE | ((auth.uid() IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM tournaments
  WHERE ((tournaments.id = tournament_matches.tournament_id) AND (tournaments.created_by = auth.uid())))))                                                  | null                                                                                                                                                                                                                                                 |
| public     | tournament_matches        | Tournament organizers can delete matches                    | PERMISSIVE | {public} | DELETE | ((auth.uid() IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM tournaments
  WHERE ((tournaments.id = tournament_matches.tournament_id) AND (tournaments.created_by = auth.uid())))))                                                  | null                                                                                                                                                                                                                                                 |
| public     | random_sessions           | Users can update own random session                         | PERMISSIVE | {public} | UPDATE | ((auth.role() = 'authenticated'::text) AND ((a_user_id = auth.uid()) OR (b_user_id = auth.uid())))                                                                                                                               | null                                                                                                                                                                                                                                                 |
| public     | random_messages           | Users can read random messages                              | PERMISSIVE | {public} | SELECT | ((auth.role() = 'authenticated'::text) AND (EXISTS ( SELECT 1
   FROM random_sessions s
  WHERE ((s.id = random_messages.session_id) AND ((s.a_user_id = auth.uid()) OR (s.b_user_id = auth.uid()))))))                          | null                                                                                                                                                                                                                                                 |
| public     | random_messages           | Users can insert random messages                            | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | ((auth.role() = 'authenticated'::text) AND (sender_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM random_sessions s
  WHERE ((s.id = random_messages.session_id) AND ((s.a_user_id = auth.uid()) OR (s.b_user_id = auth.uid()))))))                 |
| public     | shared_reels              | update own                                                  | PERMISSIVE | {public} | UPDATE | (auth.uid() = shared_by_id)                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| public     | shared_reels              | delete own                                                  | PERMISSIVE | {public} | DELETE | (auth.uid() = shared_by_id)                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| public     | shared_reel_recipients    | view recipients when recipient                              | PERMISSIVE | {public} | SELECT | (recipient_id = auth.uid())                                                                                                                                                                                                      | null                                                                                                                                                                                                                                                 |
| public     | shared_reel_recipients    | update recipients for own                                   | PERMISSIVE | {public} | UPDATE | (EXISTS ( SELECT 1
   FROM shared_reels s
  WHERE ((s.id = shared_reel_recipients.shared_reel_id) AND (s.shared_by_id = auth.uid()))))                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | shared_reels              | insert own                                                  | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (auth.uid() = shared_by_id)                                                                                                                                                                                                                          |
| public     | shared_reel_recipients    | view recipients for own                                     | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1
   FROM shared_reels s
  WHERE ((s.id = shared_reel_recipients.shared_reel_id) AND (s.shared_by_id = auth.uid()))))                                                                                           | null                                                                                                                                                                                                                                                 |
| public     | shared_reel_recipients    | insert recipients for own                                   | PERMISSIVE | {public} | INSERT | null                                                                                                                                                                                                                             | (EXISTS ( SELECT 1
   FROM shared_reels s
  WHERE ((s.id = shared_reel_recipients.shared_reel_id) AND (s.shared_by_id = auth.uid()))))                                                                                                               |
| public     | shared_reels              | Users can view shared reels (public/followers)              | PERMISSIVE | {public} | SELECT | ((share_type = 'public'::text) OR ((share_type = 'followers'::text) AND is_follower(shared_by_id, auth.uid())))                                                                                                                  | null                                                                                                                                                                                                                                                 |